### ISSUE TITLE
Latest 1.8.x release also installed on previous versions

### ISSUE THREAD

**Issue by siimav** [DMagic1/DMModuleScienceAnimateGeneric#12]
Apparently CKAN will offer the latest 1.8 release also for people who are still on earlier versions of KSP. Because of the significant changes in Unity, this will not work.
I think you will need to edit the .version file and add both `KSP_VERSION` and `KSP_VERSION_MIN` to prevent that from happening.

**Comment by DMagic1** [comment]
This doesn't have a .version file. The CKAN meta data will need to be updated, which is a CKAN problem, not mine.
