### ISSUE TITLE
In CKAN, listed as being 1.1.2 compatible

### ISSUE THREAD

**Issue by linuxgurugamer** [DMagic1/DMModuleScienceAnimateGeneric#6]
This prevents anything which depends on it from being installable in 1.1.3

**Comment by DMagic1** [comment]
Please put this on NetKAN where it will get the right attention.

**Comment by linuxgurugamer** [comment]
It's a problem in the netkan file.  I can fix it for you, but need you to confirm it is compatible with 1.1.3 (and say it's ok for me to update the file).
Thx

**Comment by DMagic1** [comment]
It works fine, you can update it.

**Comment by linuxgurugamer** [comment]
Ok, thanks
